// All the routes about the implementation for the User Module

# Get the list of Users, if the role is Admin
GET http://localhost:3000/users HTTP/1.1

###

# Get the list of Users, if the role isn't Admin
GET http://localhost:3000/users HTTP/1.1

###

# Get a user by his username
GET http://localhost:3000/users/username/marilou HTTP/1.1

###

# Get a user by his email
GET http://localhost:3000/users/email/marie@example.com HTTP/1.1

###

# Get a user by his id
GET http://localhost:3000/users/id/4 HTTP/1.1