// All the routes about the implementation for the User Module

#1 Get the list of Users, if the role is Admin
GET http://localhost:3000/users HTTP/1.1
Authorization: 
###

#2 Get the list of Users, if the role isn't Admin
GET http://localhost:3000/users HTTP/1.1
Authorization: ZnJlZGRv
###

#3 Get a user by his username (only admin or referee)
GET http://localhost:3000/users/username/marilou HTTP/1.1
Authorization: 
###

#4 Get a user by his email
GET http://localhost:3000/users/email/marie@example.com HTTP/1.1
Authorization: 
###

#5 Get a user by his id
GET http://localhost:3000/users/id/4 HTTP/1.1
Authorization: 

###

#6 Post a new user (Success version)
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Freddy", 
    "lastName": "Potiche",
    "email": "fred@example.com",
    "username": "freddo",
    "password": "Fred123"
}

###
#7 Post a new user (Fail version because the user is already created)
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "joseph", 
    "lastName": "Potiche",
    "email": "josep@example.com",
    "username": "jesepo",
    "password": "Fred123"
}

###
#8 Put : allows an admin to update any users and an user to update his/her own profile
PUT http://localhost:3000/users/3 HTTP/1.1
Authorization: 
Content-Type: application/json

{

}

###
#9 Patch : change a user's role
PATCH http://localhost:3000/users/2/role/trainer HTTP/1.1
Authorization: 

###
#10 Patch : reactivate a inactive user
PATCH http://localhost:3000/users/3/reactivate